spring:
  application:
    name: DEPARTMENT-SERVICE

server:
  port: 9001


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    hostname: localhost