spring:
  application:
    name: USER-SERVICE

server:
  port: 9002


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    hostname: localhost